In [5]:
import numpy as np
import matplotlib.pyplot as plt

import tensorflow as tf
import tensorflow_datasets as tfds
import tensorflow_hub as hub

In [6]:
classifier = hub.KerasLayer(
    "https://tfhub.dev/google/cropnet/classifier/cassava_disease_V1/2"
)

I0000 00:00:1729946063.740280 1838543 gpu_device.cc:2022] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 46679 MB memory:  -> device: 0, name: NVIDIA RTX 6000 Ada Generation, pci bus id: 0000:2a:00.0, compute capability: 8.9
I0000 00:00:1729946063.740983 1838543 gpu_device.cc:2022] Created device /job:localhost/replica:0/task:0/device:GPU:1 with 46679 MB memory:  -> device: 1, name: NVIDIA RTX 6000 Ada Generation, pci bus id: 0000:3d:00.0, compute capability: 8.9
I0000 00:00:1729946063.741517 1838543 gpu_device.cc:2022] Created device /job:localhost/replica:0/task:0/device:GPU:2 with 46679 MB memory:  -> device: 2, name: NVIDIA RTX 6000 Ada Generation, pci bus id: 0000:ab:00.0, compute capability: 8.9
I0000 00:00:1729946063.741942 1838543 gpu_device.cc:2022] Created device /job:localhost/replica:0/task:0/device:GPU:3 with 46679 MB memory:  -> device: 3, name: NVIDIA RTX 6000 Ada Generation, pci bus id: 0000:bd:00.0, compute capability: 8.9


In [7]:
classifier

In [5]:
import datasets

data = datasets.load_dataset(
    "pufanyi/cassava-leaf-disease-classification", "full", split="train"
)

In [6]:
data[0]

{'image_id': '1000015157.jpg',
 'image': <PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=800x600>,
 'label': 0}

In [10]:
from PIL import Image


def preprocess_fn(image: Image.Image):
    image = tf.convert_to_tensor(np.array(image), dtype=tf.float32)

    # Normalize [0, 255] to [0, 1]
    image = tf.cast(image, tf.float32)
    image = image / 255.0

    # Resize the images to 224 x 224
    image = tf.image.resize(image, (224, 224))

    return image


probabilities = classifier(preprocess_fn(data[0]["image"]))

In [12]:
def preprocess_fn(image: Image.Image):
    image = tf.convert_to_tensor(np.array(image), dtype=tf.float32)

    # Normalize [0, 255] to [0, 1]
    image = tf.cast(image, tf.float32)
    image = image / 255.0

    # Resize the images to 224 x 224
    image = tf.image.resize(image, (224, 224))

    # Add batch dimension
    image = tf.expand_dims(image, 0)

    return image


# Use the updated preprocess_fn
probabilities = classifier(preprocess_fn(data[0]["image"]))

2024-10-13 23:17:43.232752: I external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:531] Loaded cuDNN version 8900
W0000 00:00:1728832663.414244 1695673 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1728832663.475005 1695673 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1728832663.482192 1695673 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1728832663.489483 1695673 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1728832663.508031 1695673 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1728832663.517524 1695673 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1728832663.524642 1695673 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1728832663.531780 1695673 gpu_t

In [13]:
probabilities

<tf.Tensor: shape=(1, 6), dtype=float32, numpy=
array([[2.1407759e-01, 1.9166220e-02, 2.6541036e-02, 2.1100678e-03,
        7.3807621e-01, 2.8852362e-05]], dtype=float32)>

In [14]:
predictions = tf.argmax(probabilities, axis=-1)

In [15]:
predictions

<tf.Tensor: shape=(1,), dtype=int64, numpy=array([4])>

In [16]:
classifier

In [ ]:
# convert classifier to pytorch

import torch